apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels: 
    app: backend
spec:
  containers:
  - image: 10.108.42.150/backend # {register's cluster-ip}/{image-name}
    name: backend
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 10001
    protocol: TCP
    targetPort: 8000