apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels: 
    app: backend
spec:
  containers:
  - image: nginx # localhost:5000/backend
    name: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 10001 # 8080
    protocol: TCP
    targetPort: 80