apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels: 
    app: frontend
spec:
  containers:
  - image: 10.108.42.150/frontend # {register's cluster-ip}/{image-name}
    name: frontend
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 10002
    protocol: TCP
    targetPort: 80