apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels: 
    app: frontend
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 10002 # 8080
    protocol: TCP
    targetPort: 80