apiVersion: v1
kind: Pod
metadata:
  labels:
    app: scp # scored-planner
  name: scp # scored-planner
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: /etc/nginx/conf.d/app.conf
      name: nginx-app-conf
      subPath: app.conf
  volumes:
  - configMap:
      name: nginx-app-conf
    name: nginx-app-conf
---
apiVersion: v1
kind: Service
metadata:
  name: scp
spec: 
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: scp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-app-conf
data:
  app.conf: |
    server {
        listen 80;
        location / {
            proxy_pass http://frontend:10002;
        }
        location /api/ {
            proxy_pass http://backend:10001/;
        }
    }