apiVersion: v1
kind: Pod
metadata:
  labels:
    app: scp # scored-planner
  name: scp # scored-planner
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: /etc/nginx/nginx.conf
      name: nginx-conf
      subPath: nginx.conf
  volumes:
  - configMap:
      name: nginx-conf
    name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: scp
spec: 
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: scp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |-
    # nginx.conf 파일
    # 컨테이너 내부에 /etc/nginx/conf.d/nginx.conf 경로에 존재
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;
        include /etc/nginx/conf.d/*.conf;

        #security
        server_tokens off;

        # custom
        server {
            listen 8080;
            location / {
                proxy_pass http://frontend:10002;
            }
            location /api/ {
                proxy_pass http://backend:10001;
            }
        }

    }